import { Inter } from 'next/font/google';

import ReturnButton from '@/components/ReturnButton';
import ReduxProvider from '@/redux/Provider';
import Navbar from '@/components/Navbar';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Spotify',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <Navbar />
          {children}
        </ReduxProvider>
        <ReturnButton />
      </body>
    </html>
  );
}
